name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 11.5.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^7.0.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.5
  flutter_vector_icons: ^2.0.0

  #Map
  google_maps_flutter: ^2.6.0
  geocoding: ^2.2.2
  geolocator: ^10.0.1

  #Firebase
  firebase_core: ^2.28.0
  firebase_crashlytics: ^3.5.0
  firebase_auth: ^4.19.0
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.16.0
  firebase_pagination: ^3.1.0
  firebase_messaging: ^14.8.0

  flutter_local_notifications: ^17.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_custom_tabs: ^2.0.0+1
  syncfusion_flutter_charts: ^25.1.38
  webview_flutter: ^4.7.0
  country_picker: ^2.0.25

  #image:
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  file_picker: ^6.2.0
  lottie: ^3.1.0

  # PAYMENTS
  midpay: ^1.1.7
  phonepe_payment_sdk: ^2.0.1
  flutter_stripe: ^10.1.1
  razorpay_flutter: ^1.3.6
  flutterwave_standard: ^1.0.8
  cinetpay: ^1.0.7
  flutter_paypal_checkout:
    git:
      url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/Raj-GMITS/flutter_paystack.git
      ref: master

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1
  # flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    #- assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/upi_payment/
    - assets/lottie/

